name: Run Espresso Tests on Firebase Test Lab
permissions:
  contents: read
  checks: write
  issues: read
  pull-requests: write
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request:
    types: [ ready_for_review ]
  workflow_dispatch:
    inputs:

      target-branch:
        description: 'your target branch'
        type: string
        required: true
        default: 'master'

      flavor:
        description: 'flavor or environment'
        required: true
        type: choice
        options:
          - Stg
          - Dev
          - Tb
          - Ds1
          - Ds2
          - Ds3
          - Ds4
          - Dev1
          - Dev2
          - Dev3
          - Ds1_1
          - Ds1_2
          - Ds2_1
          - Ds2_2
          - Ds3_1
          - Ds3_2
          - Ds4_1
          - Ds4_2

jobs:
  test-trigger:

    runs-on: ubuntu-latest
    steps:
      - name: Debug trigger
        run: |
          echo "Workflow triggered!"
          echo "Event name: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body }}"