name: Run Espresso Tests on Firebase Test Lab
permissions:
  contents: read
  checks: write
  issues: read
  pull-requests: write
on:
  issue_comment:
    types: [ created ]
  pull_request_review_comment:
    types: [ created ]
  pull_request:
    types: [ ready_for_review ]

jobs:
  test-trigger:
    # Job runs only if the comment contains "/mandatoryTest"
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/mandatoryTest')
    runs-on: ubuntu-latest
    steps:
      - name: Debug trigger
        run: |
          echo "Workflow triggered!"
          echo "Event name: ${{ github.event_name }}"
          echo "Comment body: ${{ github.event.comment.body }}"